# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.10.1" # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files","--section-default=THIRDPARTY","-o=config"]
        name: Isort

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: generate-check
        name: generate-check
        entry: python generate.py -i definition.example.yml -o scratch
        language: system
        pass_filenames: false
        always_run: true
